# Generated by Django 2.1.3 on 2018-11-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20181119_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tel',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
